diversifyshop:
    target: dev
    outputs:
        dev:
            type: postgres
            host: host.docker.internal #localhost     
            user: postgres
            password: '##'
            port: 5432
            dbname: diversifyshop
            schema: dbt_juliet_dev
            threads: 4
            
#run  'dbt debug'  from within a project to test your connection

